name: trigger skillitall jenkins build job
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install semver
      run: pip install semver
    - name: Check Changes and Bump Version
      run: |
        changes=$(git diff --name-only HEAD^ HEAD)
        if [[ $changes == *"BreakingChange"* ]]; then
          export VERSION_BUMP='major'
        elif [[ $changes == *"NewFeature"* ]]; then
          export VERSION_BUMP='minor'
        else
          export VERSION_BUMP='patch'
        fi
        current_version=$(git describe --abbrev=0)
        new_version=$(semver --increment $VERSION_BUMP $current_version)
        echo "New version: $new_version"
        echo "::set-env name=NEW_VERSION::$new_version"