name: trigger skillitall jenkins build job
on:
  push:
    branches:
      - master
#  pull_request:
#    pull_request:
#      types: [ opened, synchronize ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install semver
      run: pip install semver
    - name: Check Changes and Bump Version
      run: |
        PR_NAME=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
        echo "PR_NAME: $PR_NAME"
        if [[ $PR_NAME == "BreakingChange"* ]]; then
          export VERSION_BUMP='major'
        elif [[ $PR_NAME == "minor"* ]]; then
          export VERSION_BUMP='minor'
        elif [[ $PR_NAME == "patch"* ]]; then
          export VERSION_BUMP='patch'
        else
          export VERSION_BUMP='patch'
        fi
        current_version=$(git describe --abbrev=0)
        new_version=$(python -m semver bump $VERSION_BUMP $current_version)
        echo "New version: $new_version"
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
    - name: Tag new version
      run: |
        git config --global user.email "hredi1994@gmail.com"
        git config --global user.name "redih1994"
        git tag -a ${{ env.NEW_VERSION }} -m "Bump version to ${{ env.NEW_VERSION }}"
    - name: Push tags
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/redih1994/object-detection.git
        git push origin --tags