name: Update Tag

on:
  pull_request:
    types: [opened, reopened]

jobs:
  update-tag:
    name: Update Tag
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check PR name and bump version
      id: version
      run: |
        PR_NAME=$(jq -r ".pull_request.title" "$GITHUB_EVENT_PATH")
        if [[ $PR_NAME == *"BreakingChange"* ]]; then
          export VERSION_BUMP='major'
        elif [[ $PR_NAME == *"minor"* ]]; then
          export VERSION_BUMP='minor'
        elif [[ $PR_NAME == *"patch"* ]]; then
          export VERSION_BUMP='patch'
        else
          export VERSION_BUMP='patch'
        fi
        current_version=$(git describe --abbrev=0)
        new_version=$(python -m semver bump $VERSION_BUMP $current_version)
        echo "New version: $new_version"
        echo "::set-output name=new_version::$new_version"

    - name: Create tag and push
      if: steps.version.outputs.new_version
      run: |
        git tag -a v${{ steps.version.outputs.new_version }} -m "Version ${{ steps.version.outputs.new_version }}"
        git push --tags
